# Generated by Django 3.2.5 on 2021-07-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldperson_info',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_info',
            name='username',
            field=models.CharField(default='employee', max_length=50),
        ),
        migrations.AlterField(
            model_name='oldperson_info',
            name='username',
            field=models.CharField(default='oldperson', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='password',
            field=models.CharField(default='123456', max_length=50),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='username',
            field=models.CharField(default='sysuser', max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteer_info',
            name='username',
            field=models.CharField(default='volunteer', max_length=50),
        ),
    ]
